#!/usr/bin/env bash

set -xe

# Install essential tools
apt-get update -q
apt-get upgrade -y
apt-get install -y \
    apt-transport-https \
    apt-utils \
    curl \
    git \
    zip \
    unzip \
    libfontconfig \
    xvfb \
    libgtk2.0-0 \
    libnotify-dev \
    libgconf-2-4 \
    libnss3 \
    libxss1 \
    libasound2

sh /scripts/cleanup
